****

Importing Numpy

In [ ]:
import numpy as np

****

List vs Numpy - Time Taken

In [ ]:
import numpy as np
from time import process_time

start_time_1 = process_time()
python_list = [i*i for i in range(100000)]
end_time_1 = process_time()
print('Time taken by list:', end_time_1 - start_time_1)

start_time_2 = process_time()
np_array = np.array([i*i for i in range(100000)])
end_time_2 = process_time()
print('Time taken by NumPy array:', end_time_2 - start_time_2)


Time taken by list: 0.014443310999999959
Time taken by NumPy array: 0.03830095300000025


****

Numpy Array


In [ ]:
list1=[1,2,3,4,5]
print(list1,type(list1))

np_array=np.array([1,2,3,4,5])
print(np_array,type(np_array))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
#creating a One-dimensional array
a=np.array([1,2,3,4])
print(a)
print(a.shape)

#creating a Multi-dimensional array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

#creating a Multi-dimensional array with floating data-type
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)
print(c.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)


****

Initial Placeholders in numpy arrays

In [ ]:
#Create a numpy array of zeros
a=np.zeros((2,2))
print(a)

#Create a numpy array of ones
b=np.ones((2,2))
print(b)

#Create a numpy array of particular value
c=np.full((2,2),7)
print(c)

#Create an Identity matrix
d=np.eye(2)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [ ]:
#Create a numpy array with Random values
a = np.random.random((2,2))
print(a)

#Create a numpy array with Random integer values
b = np.random.randint(1,100,(2,2))
print(b)

[[0.64620086 0.09079216]
 [0.67338187 0.36661892]]
[[22 20]
 [59 37]]


In [ ]:
#array of evenly spaced values --> specifying the number of values required
a = np.linspace(10,30,6)
print(a)

#array of evenly spaced values --> specifying the steps
b = np.arange(10,30,6)
print(b)

[10. 14. 18. 22. 26. 30.]
[10 16 22 28]


In [ ]:
# Convert a list to a numpy array
a = [10,20,30,40,50]
b = (60,70,80,90,100)

np_array1 = np.asarray(a)
print(np_array1,type(np_array1))

np_array2 = np.asarray(b)
print(np_array2,type(np_array2))

[10 20 30 40 50] <class 'numpy.ndarray'>
[ 60  70  80  90 100] <class 'numpy.ndarray'>


****

Analysing a numpy array

In [ ]:
a=np.random.randint(1,10,(2,2))
print(a)
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)

[[8 4]
 [8 1]]
<class 'numpy.ndarray'>
2
4
int64


****

Mathematcal operations on a np array

In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 22 18]
 [19 23 21]
 [28 13 22]]
[[ -5 -16  -4]
 [-17  -5  -5]
 [-10  -7 -12]]
[[126  57  77]
 [ 18 126 104]
 [171  30  85]]
[[0.64285714 0.15789474 0.63636364]
 [0.05555556 0.64285714 0.61538462]
 [0.47368421 0.3        0.29411765]]


****

Array Manipulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)

#transpose
a=np.transpose(array)
print(a)

#reshape
b=array.reshape(3,2)
print(b)

[[3 5 6]
 [8 0 6]]
[[3 8]
 [5 0]
 [6 6]]
[[3 5]
 [6 8]
 [0 6]]
